#!/usr/bin/env sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

if [ -z $FILES ]; then
    exit
fi

echo $FILES | xargs ./node_modules/.bin/prettier --ignore-unknown --write
echo $FILES | xargs git add