#!/usr/bin/env sh

FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')

if [ -z $FILES ]; then
    exit
fi

if [ -f "package.json" ]; then
    if [ -f "bun.lockb" ]; then
        PKGM=bun
    fi

    echo $FILES | xargs ${PKGM:-npm} run format --ignore-unknown --write
    echo $FILES | xargs git add
fi